"""The application icon, for the window and the taskbar.

Generated by ``scripts/make_icons.py`` and committed under ``assets/icons``, so
the app looks the same running from a checkout as it does installed. Found
beside the executable as well as in the source tree, because a frozen build
unpacks its data next to the binary rather than next to the code.
"""

from __future__ import annotations

import sys
from pathlib import Path

from PySide6.QtGui import QIcon

#: Largest first: QIcon picks per context, and having the big ones present is
#: what stops a Retina dock scaling a 32px image up.
_SIZES = (1024, 512, 256, 128, 64, 48, 32, 16)


def icons_dir() -> Path | None:
    frozen = getattr(sys, "_MEIPASS", None)
    roots = [Path(frozen) / "assets" / "icons"] if frozen else []
    roots.append(Path(__file__).resolve().parents[4] / "assets" / "icons")
    return next((root for root in roots if root.is_dir()), None)


def app_icon() -> QIcon:
    """Every size we ship, in one QIcon (empty if the assets are missing)."""
    icon = QIcon()
    root = icons_dir()
    if root is None:
        return icon
    for size in _SIZES:
        path = root / f"icon_{size}.png"
        if path.is_file():
            icon.addFile(str(path))
    return icon
